 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
     steps:
       - checkout
       - run: dotnet build
      #  - run:
          # command: remove-item alias:curl; curl https://punch-line.co.uk/hooks/redeploy-punchline-backend
          # when: on_success
       - store_artifacts:
          path: /bin