version: 2.1

orbs:
     win: circleci/windows@2.2.0
     sops: theskimm/sops@0.0.2
     aws-cli: circleci/aws-cli@2.0

jobs:
     decrypt-secrets:
          docker:
               - image: buildpack-deps:trusty
          steps:
          - attach_workspace:
               at: .
          - checkout
          - aws-cli/setup:
               profile-name: "$AWS_CREDENTIAL_PROFILE"
          - sops/aws_decrypt:
               aws_access_key_id: AWS_ACCESS_KEY_ID
               aws_secret_access_key: AWS_SECRET_ACCESS_KEY
               input_file_path: "~/project/firebase-admin-sdk.encrypted.json"
               output_file_path: "~/project/firebase-admin-sdk.json"
               output_type: "json"
               sops_release_url: https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux
          - persist_to_workspace:
               paths: .
               root: .

     build:
          executor: win/default
          steps:
               - run: dotnet build
               - run: dotnet test
               - store_artifacts:
                    path: /bin
# WorkFlows
workflows:
     # Only runs on the develop branch 
     build_and_test:
          jobs: 
               - decrypt-secrets
               - build:
                    requires:
                         - decrypt-secrets