 version: 2.1

 orbs:
  win: circleci/windows@2.2.0
  sops: theskimm/sops@0.0.2

 jobs:
   build:
     executor: win/default
     steps:
       - checkout
      #  - run: ./scripts/ci-aws-config.sh
       - sops/aws_decrypt:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          input_file_path: "./firebase-admin-sdk.encrypted.json"
          output_file_path: "./firebase-admin-sdk.json"
          output_type: "json"
          sops_release_url: https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.exe
       - run: dotnet build
       - run: dotnet test

      #  - run:
          # command: remove-item alias:curl; curl https://punch-line.co.uk/hooks/redeploy-punchline-backend
          # when: on_success
       - store_artifacts:
          path: /bin