INSERT INTO "Categories"("Name","Id","Image") VALUES ('Animal',1,'https://joke-categories-547.s3.amazonaws.com/animal.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Other / Misc',2,'https://joke-categories-547.s3.amazonaws.com/1.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Bar',3,'https://joke-categories-547.s3.amazonaws.com/bar.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('One Liners',4,'https://joke-categories-547.s3.amazonaws.com/1.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Puns',5,'https://joke-categories-547.s3.amazonaws.com/1.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Lawyer',6,'https://joke-categories-547.s3.amazonaws.com/1.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Sports',7,'https://joke-categories-547.s3.amazonaws.com/1.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Medical',8,'https://joke-categories-547.s3.amazonaws.com/doctor.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('News / Politics',9,'https://joke-categories-547.s3.amazonaws.com/politics.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Men / Women',10,'https://joke-categories-547.s3.amazonaws.com/dad.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Gross',11,'https://joke-categories-547.s3.amazonaws.com/1.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Blonde',12,'https://joke-categories-547.s3.amazonaws.com/blonde.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Yo Momma',13,'https://joke-categories-547.s3.amazonaws.com/insult.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Redneck',14,'https://joke-categories-547.s3.amazonaws.com/redneck.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Religious',15,'https://joke-categories-547.s3.amazonaws.com/priest.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('At Work',16,'https://joke-categories-547.s3.amazonaws.com/office.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('College',17,'https://joke-categories-547.s3.amazonaws.com/college.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Lightbulb',18,'https://joke-categories-547.s3.amazonaws.com/lightbulb.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Children',19,'https://joke-categories-547.s3.amazonaws.com/children.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Insults',20,'https://joke-categories-547.s3.amazonaws.com/insult.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Knock-Knock',21,'https://joke-categories-547.s3.amazonaws.com/knock-knock.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Tech',22,'https://joke-categories-547.s3.amazonaws.com/robot.svg');
INSERT INTO "Categories"("Name","Id","Image") VALUES ('Yo Mama',23,'https://joke-categories-547.s3.amazonaws.com/insult.svg');
