INSERT INTO `Categories` (`Id`, `Name`, `Image`) VALUES
(1, 'Animal', 'https://web.punch-line.co.uk/categories/animal.svg'),
(2, 'Other / Misc', 'https://web.punch-line.co.uk/categories/1.svg'),
(3, 'Bar', 'https://web.punch-line.co.uk/categories/bar.svg'),
(4, 'One Liners', 'https://web.punch-line.co.uk/categories/1.svg'),
(5, 'Puns', 'https://web.punch-line.co.uk/categories/1.svg'),
(6, 'Lawyer', 'https://web.punch-line.co.uk/categories/1.svg'),
(7, 'Sports', 'https://web.punch-line.co.uk/categories/1.svg'),
(8, 'Medical', 'https://web.punch-line.co.uk/categories/doctor.svg'),
(9, 'News / Politics', 'https://web.punch-line.co.uk/categories/politics.svg'),
(10, 'Men / Women', 'https://web.punch-line.co.uk/categories/dad.svg'),
(11, 'Gross', 'https://web.punch-line.co.uk/categories/1.svg'),
(12, 'Blonde', 'https://web.punch-line.co.uk/categories/blonde.svg'),
(13, 'Yo Momma', 'https://web.punch-line.co.uk/categories/insult.svg'),
(14, 'Redneck', 'https://web.punch-line.co.uk/categories/redneck.svg'),
(15, 'Religious', 'https://web.punch-line.co.uk/categories/priest.svg'),
(16, 'At Work', 'https://web.punch-line.co.uk/categories/office.svg'),
(17, 'College', 'https://web.punch-line.co.uk/categories/college.svg'),
(18, 'Lightbulb', 'https://web.punch-line.co.uk/categories/lightbulb.svg'),
(19, 'Children', 'https://web.punch-line.co.uk/categories/children.svg'),
(20, 'Insults', 'https://web.punch-line.co.uk/categories/insult.svg'),
(21, 'Knock-Knock', 'https://web.punch-line.co.uk/categories/knock-knock.svg'),
(22, 'Tech', 'https://web.punch-line.co.uk/categories/robot.svg');